export const EMAIL_CHANGED = 'emailChanged'
export const PASSWORD_CHANGED = 'passwordChanged'
export const LOGIN_USER_SUCCESS = 'loginUserSuccess'
export const LOGIN_USER_FAIL = 'loginUserFail'
export const LOGIN_USER_START = 'loginUserStart'
export const REQUEST_API_DATA = 'requestApiData'
