export const MAIN = 'Main'
export const LOGGED_IN = 'Loggedin'
export const ADD_ADDRESS_1 = 'Add Address 1'
export const ADD_ADDRESS_2 = 'Add Address 2'
export const MESSAGE = 'Message'
export const PAYMENT = 'Payment'
